server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/jenkins
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml      #\u4F7F\u7528\u7684Mapper\u6587\u4EF6\u4F4D\u7F6E
  typeAliasesPackage: com.liusl.model           #\u5B83\u4E00\u822C\u5BF9\u5E94\u6211\u4EEC\u7684\u5B9E\u4F53\u7C7B\u6240\u5728\u7684\u5305\uFF0C\u8FD9\u4E2A\u65F6\u5019\u4F1A\u81EA\u52A8\u7B80\u5355\u7C7B\u540D\u4F5C\u4E3A\u5305\u62EC\u5305\u540D\u7684\u522B\u540D\u53D6\u5BF9\u5E94\u5305\u4E2D\u4E0D\u5305\u62EC\u5305\u540D\u7684\u522B\u540D
  #\u5EF6\u8FDF\u52A0\u8F7D
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
management:
  security:
    enabled: false
