eureka:
  client:
    com.liusl.service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
   enabled: true
##Rabbit Mq配置信息
spring:
  rabbitmq:
    host: 10.99.246.99
    port: 5672
    username: guest
    password: guest

# 说明：请务必注意，在Spring Cloud Dalston中，Feign默认是不开启Hystrix的。
# 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
# 而，Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。