spring:
  application:
    name: microservice-auth-server
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth-test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.122.23.8
    port: 6379
    database: 2
logging:
  level:
    org.springframework: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/