eureka:
  client:
    com.liusl.service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
management:
  security:
    enabled: false
zuul:
  routes:
    movie-a:
      path: /movie-feign/**
      serviceId: CONSUMER-FEIGN
    movie-b:
      path: /movie/**
      serviceId: PROVIDER
#zuul:
#  routes:
#    user-route:
#      com.liusl.service-id: consumer-ribbon
#      path: /api/**
#  prefix: /v1