eureka:
  client:
    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
zuul:
  routes:
    movie-a:
      path: /movie-feign/**
      serviceId: CONSUMER-FEIGN
    movie-b:
      path: /movie/**
      serviceId: PROVIDER
    consumer-ribbon-hystrix-mq:
      path: /hystrix/**
      serviceId: MICROSERVICE-HYSTRIX-TURBINE-MQ
    auth:
      path: /auth-service/**
      serviceId: microservice-auth-server
#zuul:
#  routes:
#    user-route:
#      com.liusl.service-id: consumer-ribbon
#      path: /api/**
#  prefix: /v1