eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  app-config: CONSUMER-RIBBON-HYSTRIX,CONSUMER-FEIGN-FALLBACK
  cluster-name-expression: "'default'"