eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

##Rabbit Mq配置信息
spring:
  rabbitmq:
    host: 10.99.246.99
    port: 5672
    username: guest
    password: guest